# Generated by Django 5.0.5 on 2024-09-19 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilinguismo_programa',
            name='bil_modalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personas.modalidad'),
        ),
    ]
