# Generated by Django 5.0.5 on 2024-09-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metas_formacion',
            name='met_centro_formacion',
        ),
    ]
