# Generated by Django 5.0.5 on 2024-09-23 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_remove_metas_formacion_met_centro_formacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='metas_formacion',
            name='met_centro_formacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personas.centro_de_formacion'),
        ),
    ]
