# Generated by Django 5.0.5 on 2024-09-24 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_metas_formacion_met_centro_formacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p04',
            name='fecha_p04',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
